// Generated by scripts/sync-shared.mjs from lib/site — edit the original there, not this copy.
// The AI's change sets: what it may propose (a few kinds of operation on the content document), how they are applied
// and checked, and what they cost. Shared with the Edge Functions (see scripts/sync-shared.mjs); the price comes from
// what a change set actually contains, never from what the model says it costs.
import { z } from "zod";
import { idSchema, siteDataSchema, type Collection, type SiteData, type SiteImage } from "./schema.ts";
import { applyPatches, getAt, isPrefix, pathKey, type ContentPath, type Patch } from "./paths.ts";
import { describePath } from "./changes.ts";
import { sectionTypeLabels } from "./labels.ts";
import { PRICES, priceLabels, type PriceKey } from "./pricing.ts";
import { list } from "./collection.ts";
import { RESERVED_SLUGS } from "./pages.ts";

// ---------------------------------------------------------------------------------------------------------------------
// The format

const pathSchema = z.array(z.string().min(1).max(80)).min(1).max(14);
const placeSchema = z.enum(["first", "last", "after"]);

export const operationSchema = z.discriminatedUnion("op", [
  /** Sets one part of the document (a text, a link, a whole section …) to a new value. */
  z.object({ op: z.literal("set"), path: pathSchema, valueJson: z.string().max(200_000) }),
  /** Adds an item to a list (a section to a page, a question to a FAQ …). */
  z.object({
    op: z.literal("insert"),
    path: pathSchema,
    id: z.string().max(64),
    place: placeSchema,
    afterId: z.string().max(64),
    itemJson: z.string().max(200_000),
  }),
  /** Removes an item from a list. */
  z.object({ op: z.literal("remove"), path: pathSchema, id: z.string().max(64) }),
  /** Moves an item within its list. */
  z.object({ op: z.literal("move"), path: pathSchema, id: z.string().max(64), place: placeSchema, afterId: z.string().max(64) }),
]);
export type Operation = z.infer<typeof operationSchema>;

export const changeSetSchema = z.object({
  summary: z.string().min(1).max(3000),
  operations: z.array(operationSchema).max(80),
  imagesNeeded: z.array(z.string().max(400)).max(12),
});
export type ChangeSet = z.infer<typeof changeSetSchema>;

const stringArray = { type: "array", items: { type: "string" } };
const placeEnum = { type: "string", enum: ["first", "last", "after"] };

/** The same format as JSON Schema, for the model's structured output (every object closed, every field required). */
export const changeSetJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: ["summary", "operations", "imagesNeeded"],
  properties: {
    summary: { type: "string" },
    operations: {
      type: "array",
      items: {
        anyOf: [
          {
            type: "object",
            additionalProperties: false,
            required: ["op", "path", "valueJson"],
            properties: { op: { type: "string", const: "set" }, path: stringArray, valueJson: { type: "string" } },
          },
          {
            type: "object",
            additionalProperties: false,
            required: ["op", "path", "id", "place", "afterId", "itemJson"],
            properties: {
              op: { type: "string", const: "insert" },
              path: stringArray,
              id: { type: "string" },
              place: placeEnum,
              afterId: { type: "string" },
              itemJson: { type: "string" },
            },
          },
          {
            type: "object",
            additionalProperties: false,
            required: ["op", "path", "id"],
            properties: { op: { type: "string", const: "remove" }, path: stringArray, id: { type: "string" } },
          },
          {
            type: "object",
            additionalProperties: false,
            required: ["op", "path", "id", "place", "afterId"],
            properties: { op: { type: "string", const: "move" }, path: stringArray, id: { type: "string" }, place: placeEnum, afterId: { type: "string" } },
          },
        ],
      },
    },
    imagesNeeded: stringArray,
  },
} as const;

/** The planning answer: what the request is, the reply to the owner and, for a change, what it consists of. */
export const planKinds = ["minorText", "rewriteSection", "theme", "element", "layout", "seo", "standardSection", "advancedSection", "page"] as const;
export const planSchema = z.object({
  reply: z.string().min(1).max(6000),
  kind: z.enum(["answer", "clarify", "change"]),
  summary: z.string().max(1000),
  items: z.array(z.object({ kind: z.enum(planKinds), description: z.string().max(300) })).max(40),
});
export type Plan = z.infer<typeof planSchema>;

export const planJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: ["reply", "kind", "summary", "items"],
  properties: {
    reply: { type: "string" },
    kind: { type: "string", enum: ["answer", "clarify", "change"] },
    summary: { type: "string" },
    items: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["kind", "description"],
        properties: { kind: { type: "string", enum: planKinds }, description: { type: "string" } },
      },
    },
  },
} as const;

// ---------------------------------------------------------------------------------------------------------------------
// Prices

export interface PriceLine {
  key: PriceKey;
  label: string;
  credits: number;
}

export function priceOfPlan(plan: Plan): { lines: PriceLine[]; total: number } {
  if (plan.kind !== "change") return { lines: [], total: 0 };
  const lines = plan.items.map((item) => ({ key: item.kind, label: item.description || priceLabels[item.kind], credits: PRICES[item.kind] }));
  return { lines, total: lines.reduce((sum, line) => sum + line.credits, 0) };
}

const advancedSections = new Set(["team", "gallery", "pricelist", "testimonials"]);

/** JSON with every object's keys in order, so that two equal values always read the same (the database sorts keys). */
function canonical(value: unknown): string {
  return JSON.stringify(value, (_key, item) =>
    item && typeof item === "object" && !Array.isArray(item) ? Object.fromEntries(Object.keys(item).sort().map((key) => [key, item[key]])) : item
  );
}

/** Every leaf (text, number, flag) that differs between two values, with its path. */
function changedLeaves(before: unknown, after: unknown, path: ContentPath = []): { path: ContentPath; size: number }[] {
  if (canonical(before) === canonical(after)) return [];
  const isObject = (value: unknown) => value !== null && typeof value === "object" && !Array.isArray(value);
  if (isObject(before) && isObject(after)) {
    const keys = new Set([...Object.keys(before as object), ...Object.keys(after as object)]);
    return Array.from(keys).flatMap((key) => changedLeaves((before as Record<string, unknown>)[key], (after as Record<string, unknown>)[key], [...path, key]));
  }
  const size = Math.max(JSON.stringify(after ?? "").length, JSON.stringify(before ?? "").length);
  return [{ path, size }];
}

/** The unit a field belongs to for pricing: a section, an item of a site-wide list, or a part such as the footer. */
function unitOf(path: ContentPath): ContentPath {
  if (path[0] === "pages" && path[3] === "sections" && path[5]) return path.slice(0, 6);
  if (path[0] === "pages") return path.slice(0, 3);
  if ((path[0] === "services" || path[0] === "uppdrag" || path[0] === "certificates") && path[1] === "items" && path[2]) return path.slice(0, 3);
  return path.slice(0, 1);
}

/**
 * What a change set costs, from what it does: each new page, section and list item, each removal, each rewritten or
 * adjusted section, colours and fonts, search texts. Inside something new, nothing is counted twice.
 */
export function priceChangeSet(before: SiteData, after: SiteData, operations: Operation[]): { lines: PriceLine[]; total: number } {
  const lines: PriceLine[] = [];
  const created: ContentPath[] = [];
  const add = (key: PriceKey, label: string) => lines.push({ key, label, credits: PRICES[key] });

  for (const operation of operations) {
    if (operation.op !== "insert") continue;
    const target = [...operation.path, "items", operation.id];
    if (created.some((prefix) => isPrefix(prefix, target))) continue;
    created.push(target);
    const item = getAt(after, target) as Record<string, unknown> | undefined;
    if (operation.path.length === 1 && operation.path[0] === "pages") {
      add("page", `Ny undersida: ${String(item?.title ?? operation.id)}`);
    } else if (operation.path[0] === "pages" && operation.path[3] === "sections" && operation.path.length === 4) {
      const type = String(item?.type ?? "");
      const name = sectionTypeLabels[type as keyof typeof sectionTypeLabels]?.label ?? type;
      add(advancedSections.has(type) ? "advancedSection" : "standardSection", `Ny sektion: ${name}`);
    } else {
      add("element", `Nytt: ${describePath(after, target)}`);
    }
  }

  for (const operation of operations) {
    if (operation.op !== "remove") continue;
    const target = [...operation.path, "items", operation.id];
    add("element", `Borttaget: ${describePath(before, target)}`);
  }

  const moved = new Set(operations.filter((operation) => operation.op === "move").map((operation) => pathKey(operation.path)));
  for (const key of moved) add("minorText", `Ny ordning: ${describePath(after, key.split("."))}`);

  // Changed fields, counted per section or part, outside anything new or removed.
  const removed = operations.filter((operation) => operation.op === "remove").map((operation) => [...operation.path, "items", operation.id]);
  const leaves = changedLeaves(before, after).filter(
    (leaf) =>
      !created.some((prefix) => isPrefix(prefix, leaf.path)) &&
      !removed.some((prefix) => isPrefix(prefix, leaf.path)) &&
      leaf.path[leaf.path.length - 1] !== "order"
  );
  let theme = false;
  const seoUnits = new Set<string>();
  const units = new Map<string, { path: ContentPath; fields: number; size: number; layout: boolean }>();
  for (const leaf of leaves) {
    if (leaf.path[0] === "theme") {
      theme = true;
      continue;
    }
    const seoAt = leaf.path.indexOf("seo");
    if (seoAt > 0) {
      seoUnits.add(pathKey(leaf.path.slice(0, seoAt)));
      continue;
    }
    const unit = unitOf(leaf.path);
    const key = pathKey(unit);
    const entry = units.get(key) ?? { path: unit, fields: 0, size: 0, layout: false };
    entry.fields += 1;
    entry.size += leaf.size;
    // A section that became another kind of section is a rebuilt layout.
    if (leaf.path.length === unit.length + 1 && leaf.path[leaf.path.length - 1] === "type") entry.layout = true;
    units.set(key, entry);
  }
  if (theme) add("theme", "Färger eller typsnitt");
  for (const key of seoUnits) add("seo", `SEO: ${describePath(after, key.split("."))}`);
  for (const unit of units.values()) {
    const where = describePath(after, unit.path);
    if (unit.layout) add("layout", `Ny layout: ${where}`);
    else if (unit.fields >= 3 || unit.size > 240) add("rewriteSection", `Omskriven text: ${where}`);
    else for (let i = 0; i < unit.fields; i++) add("minorText", `Justerad text: ${where}`);
  }

  if (lines.length === 0 && operations.length > 0) add("minorText", "Mindre justering");
  return { lines, total: lines.reduce((sum, line) => sum + line.credits, 0) };
}

// ---------------------------------------------------------------------------------------------------------------------
// Images: the model sees each image without its size variants; they are put back here from the images it may use.

function isImageLike(value: unknown): value is Record<string, unknown> & { src: string } {
  return Boolean(value && typeof value === "object" && !Array.isArray(value) && typeof (value as { src?: unknown }).src === "string" && "alt" in (value as object));
}

/** Every image in the document, by its address. */
export function imagesBySrc(doc: unknown, into = new Map<string, SiteImage>()): Map<string, SiteImage> {
  const walk = (node: unknown) => {
    if (isImageLike(node) && Array.isArray((node as { variants?: unknown }).variants)) {
      into.set(node.src, node as unknown as SiteImage);
      return;
    }
    if (node && typeof node === "object") for (const value of Object.values(node as object)) walk(value);
  };
  walk(doc);
  return into;
}

/** The document as the model reads it: images without their size variants, so it stays short. */
export function compactForModel(doc: SiteData): unknown {
  const walk = (node: unknown): unknown => {
    if (isImageLike(node) && Array.isArray((node as { variants?: unknown }).variants)) {
      const { src, alt, focus } = node as unknown as SiteImage;
      return focus ? { src, alt, focus } : { src, alt };
    }
    if (Array.isArray(node)) return node.map(walk);
    if (node && typeof node === "object") return Object.fromEntries(Object.entries(node as object).map(([key, value]) => [key, walk(value)]));
    return node;
  };
  return walk(doc);
}

/** Puts the size variants back on every image in a value; an unknown address is reported, not invented. */
function restoreImages(value: unknown, known: Map<string, SiteImage>, problems: string[], where: string): unknown {
  if (isImageLike(value)) {
    const original = known.get(value.src);
    if (!original) {
      problems.push(`${where}: the image "${value.src}" is not one of the site's images or the attached ones. Use an existing image's src exactly, or leave a nullable image null and list what is needed in imagesNeeded.`);
      return value;
    }
    const alt = typeof value.alt === "string" ? value.alt : original.alt;
    const focus = typeof value.focus === "string" ? value.focus : original.focus;
    return { ...original, alt, ...(focus ? { focus } : {}) };
  }
  if (Array.isArray(value)) return value.map((item) => restoreImages(item, known, problems, where));
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value as object).map(([key, item]) => [key, restoreImages(item, known, problems, where)]));
  }
  return value;
}

// ---------------------------------------------------------------------------------------------------------------------
// Applying

function parseJson(text: string, where: string, problems: string[]): { ok: true; value: unknown } | { ok: false } {
  try {
    return { ok: true, value: JSON.parse(text) };
  } catch {
    problems.push(`${where}: the JSON in the string is not valid JSON.`);
    return { ok: false };
  }
}

function isCollection(value: unknown): value is Collection<unknown> {
  return Boolean(value && typeof value === "object" && Array.isArray((value as Collection<unknown>).order) && typeof (value as Collection<unknown>).items === "object");
}

function placed(order: string[], id: string, place: "first" | "last" | "after", afterId: string, problems: string[], where: string): string[] | null {
  const without = order.filter((other) => other !== id);
  if (place === "first") return [id, ...without];
  if (place === "last") return [...without, id];
  const index = without.indexOf(afterId);
  if (index < 0) {
    problems.push(`${where}: afterId "${afterId}" is not in this list (ids: ${without.join(", ") || "none"}).`);
    return null;
  }
  return [...without.slice(0, index + 1), id, ...without.slice(index + 1)];
}

/** Internal links that lead nowhere: a page, service or start-page section that does not exist. */
export function brokenLinks(site: SiteData): { path: ContentPath; href: string }[] {
  const pages = new Set(list(site.pages).map((page) => page.slug));
  const services = new Set(list(site.services).map((service) => service.slug));
  const home = list(site.pages).find((page) => page.slug === "");
  const homeAnchors = new Set(home ? list(home.sections).map((section) => section.anchor).filter(Boolean) : []);
  const found: { path: ContentPath; href: string }[] = [];
  const check = (href: string, path: ContentPath) => {
    if (!href.startsWith("/")) return;
    const [address, anchor] = href.split("#");
    const parts = address.replace(/^\/+|\/+$/g, "").split("/").filter(Boolean);
    let ok: boolean;
    if (parts.length === 0) ok = !anchor || homeAnchors.has(anchor);
    else if (parts[0] === "tjanster" && parts.length === 2) ok = services.has(parts[1]);
    else ok = parts.length === 1 && pages.has(parts[0]);
    if (!ok) found.push({ path, href });
  };
  const walk = (node: unknown, path: ContentPath) => {
    if (!node || typeof node !== "object") return;
    for (const [key, value] of Object.entries(node as object)) {
      if ((key === "href" || key === "breadcrumbHref") && typeof value === "string") check(value, [...path, key]);
      else walk(value, [...path, key]);
    }
  };
  walk(site, []);
  return found;
}

export interface AppliedChangeSet {
  doc: SiteData | null;
  patches: Patch[];
  /** What is wrong, in words the model can act on (empty when the change set is good). */
  problems: string[];
}

/**
 * Applies the operations to the draft one after another and checks the result against the content schema and the
 * rules the schema cannot express (ids, page addresses, links, images). The patches are what publishing applies.
 */
export function applyChangeSet(draft: SiteData, operations: Operation[], knownImages: Map<string, SiteImage>): AppliedChangeSet {
  const problems: string[] = [];
  const patches: Patch[] = [];
  let doc: unknown = draft;
  const step = (more: Patch[]) => {
    patches.push(...more);
    doc = applyPatches(doc, more);
  };

  operations.forEach((operation, index) => {
    const where = `Operation ${index + 1} (${operation.op} ${operation.path.join(".")})`;
    if (operation.path[0] === "schemaVersion") {
      problems.push(`${where}: schemaVersion cannot be changed.`);
      return;
    }
    if (operation.op === "set") {
      if (operation.path.length < 2) {
        problems.push(`${where}: set a part inside "${operation.path[0]}", not the whole of it.`);
        return;
      }
      const parsed = parseJson(operation.valueJson, where, problems);
      if (!parsed.ok) return;
      step([{ path: operation.path, op: "set", value: restoreImages(parsed.value, knownImages, problems, where) }]);
      return;
    }
    const collection = getAt(doc, operation.path);
    if (!isCollection(collection)) {
      problems.push(`${where}: the path does not lead to a list ({order, items}).`);
      return;
    }
    if (operation.op === "insert") {
      if (!idSchema.safeParse(operation.id).success) {
        problems.push(`${where}: the id "${operation.id}" must be lowercase letters, digits and hyphens.`);
        return;
      }
      if (Object.prototype.hasOwnProperty.call(collection.items, operation.id)) {
        problems.push(`${where}: the id "${operation.id}" is already used in this list.`);
        return;
      }
      const parsed = parseJson(operation.itemJson, where, problems);
      if (!parsed.ok) return;
      const order = placed(collection.order, operation.id, operation.place, operation.afterId, problems, where);
      if (!order) return;
      step([
        { path: [...operation.path, "items", operation.id], op: "set", value: restoreImages(parsed.value, knownImages, problems, where) },
        { path: [...operation.path, "order"], op: "set", value: order },
      ]);
      return;
    }
    if (!collection.order.includes(operation.id)) {
      problems.push(`${where}: there is no item "${operation.id}" in this list (ids: ${collection.order.join(", ") || "none"}).`);
      return;
    }
    if (operation.op === "remove") {
      step([
        { path: [...operation.path, "items", operation.id], op: "delete" },
        { path: [...operation.path, "order"], op: "set", value: collection.order.filter((id) => id !== operation.id) },
      ]);
      return;
    }
    const order = placed(collection.order, operation.id, operation.place, operation.afterId, problems, where);
    if (order) step([{ path: [...operation.path, "order"], op: "set", value: order }]);
  });

  const parsed = siteDataSchema.safeParse(doc);
  if (!parsed.success) {
    for (const issue of parsed.error.issues.slice(0, 15)) {
      const path = issue.path.map(String);
      problems.push(`The result breaks the content rules at ${path.join(".") || "(top)"} (${describePath(doc, path)}): ${issue.message}`);
    }
    return { doc: null, patches, problems };
  }
  const site = parsed.data;

  // Page addresses: unique, and never one the site itself uses.
  const slugs = list(site.pages).map((page) => page.slug);
  slugs.forEach((slug, index) => {
    if (slugs.indexOf(slug) !== index) problems.push(`Two pages have the address "/${slug}".`);
    if (slug && RESERVED_SLUGS.includes(slug)) problems.push(`The page address "/${slug}" is reserved by the site.`);
  });
  if (!slugs.includes("")) problems.push("The start page (slug \"\") must remain.");
  const serviceSlugs = list(site.services).map((service) => service.slug);
  serviceSlugs.forEach((slug, index) => {
    if (serviceSlugs.indexOf(slug) !== index) problems.push(`Two services have the address "/tjanster/${slug}".`);
  });
  for (const link of brokenLinks(site)) {
    problems.push(`The link "${link.href}" at ${link.path.join(".")} leads to a page, service or start-page section that does not exist.`);
  }
  return { doc: problems.length > 0 ? null : site, patches, problems };
}
